### PR TITLE
allow to subscribe to all events via '*'

### PR DESCRIPTION
**Pull request by yanick**
Can be useful to either catch all events,
or implement more complex event matching.
E.g.

```
    $emitter->on('*' => sub {
            my $event = shift;
            next unless $event->name =~ /^foo_/;

            ...
    });
```

### CODE REVIEW

**Comment by preaction** [comment]
I'm neutral on this. I can see the value, but it increases the amount of magic in the emitter. If someone wants this, its easy enough to 'after emit_args => sub { return if $_[1] eq "*"; shift->emit_args( "*", @_ ) }'

**Comment by yanick** [comment]
Good point.  Would probably do a nice addition to the POD in a "recipe" section. Want me to veer my patch in that direction?

**Comment by preaction** [comment]
I just had an idea that might revive something similar to this: I have a project called [Mercury](http://metacpan.org/pod/Mercury) that does pub/sub messaging via WebSockets. One of its interesting features is that if you subscribe to `/foo`, you get all messages sent to `/foo`, but also any path inside `/foo/*` like `/foo/bar` and `/foo/bar/baz`.

So, we could create a class like `Beam::Emitter::Tree` or `Beam::Emitter::Path` that did the same thing: Someone sends a message to `/foo/bar/baz` and it's first picked up by listeners of `/foo/bar/baz`, then sent to listeners of `/foo/bar`, and then `/foo` and finally the catch-all listeners subscribed to `/` (which would replace `*` from this PR). Any listener calling `$event->stop` would stop this propagation.

Now that I've written it all down, as fun as I find this idea, it seems more appropriate for its own distribution...

So, I'll add a cookbook with this recipe, and then we can close this.

**Comment by yanick** [comment]
Groovy!

**Comment by preaction** [comment]
Alright, I've got a cookbook entry in now, but I had to make a change to the Emitter code: The `*` catch-all in the cookbook creates a brand-new Event object that has the same `name` as the original event.

I think this is a good idea, but I'm not completely sure. Would the catch-all listener want to know that the event it got was from the catch-all `emit()` call? Should it forward the _exact_ same Event object using `emit_args` instead so that the `refaddr` can be compared to de-duplicate if necessary? 

These questions seem to indicate that it might actually be complex enough for its own module, and not just a cookbook entry... But the possible debate over the answers might mean it's better to just explain these things in the Cookbook itself...

**Pull request closed without merging**
